
version: '3'

services:

  app:
    build: ./.docker/app
    container_name: app
    entrypoint: /docker-entrypoint.sh
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on: 
      - db
      
  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:81"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - app-network
    environment:
      - PMA_HOST=db

  db:
    build: ./.docker/mysql
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=trasaction_challenge
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
